### ISSUE TITLE
Use protobuf.js package instead of grpc loader

### ISSUE THREAD

**Issue by omrishtam** [meateam/file-service#52]
- [x] compile proto to ts+js
- [x] Use protobuf.js package instead of grpc loader
- [x] more...?

**Comment by Shahar-Y** [comment]
protoc seems to change the field names when creating the js and ts files for the static linking of the code. 
Meaning, if I have a field name 'createdAt' in file.proto it will change to 'createdat' in the file_pb.js file.
Also, if I call the field 'created_at', it will change to 'createdAt'.
That means that in order to statically load the .proto file, I need to change file.proto, and you will be affected as well.

**Comment by AllKinds** [comment]
In case of required change in API Gateway service, change the API service accordingly
