### ISSUE TITLE
Generate key request - should save uploads in a collection

### ISSUE THREAD

**Issue by omerzamir** [meateam/file-service#8]
When a client generates a key it should be saved to the database with the key being the upload id and the fields `bucket` and `key`.
This collection is needed for managing ongoing uploads, for aborting and completing them without the client needing to be aware of the bucket and key we are storing.

## Functions to implement
- [x] Fix generate key to store the key with bucket.
- [x] Update upload with upload id.
- [x] Get upload by its id for retrieving bucket and key by an upload id given by the client
- [x] Delete upload by its id for aborting or completion of an upload

**Comment by Shahar-Y** [comment]
After consulting with @AllKinds  ,we have decided that generate key should not store the key but only return it. Also, no need for update because there is only a creation of the  upload in the database.
Only thing left is to figure out why unique is not enforced with key and uploadID and how to fix it.
Other than that, the tests pass and I wrote some new ones.

**Comment by Shahar-Y** [comment]
Done
